name: Puppet E2E CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [18.x]
        os: [ubuntu-latest]

    steps:
    - uses: browser-actions/setup-chrome@latest
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install Root Dependencies
      run: npm install

    - name: Bootstrap All Packages
      run: npm run bootstrap

    - name: Build All Packages
      run: CI=false npm run build

    - name: Execute Unit & Integration Tests
      run: npm run test

    - name: Execute Puppet E2E
      run: npm run e2e:puppet
      env:
        CI: true
